version: "2"

run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    # Default (already enabled, but explicit)
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Security
    - gosec
    # Code quality
    - misspell
    - unconvert
    - unparam
    - bodyclose
    - nilerr
    - errorlint
    # Maintainability
    - gocyclo
    - maintidx
    - nestif

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports

linters-settings:
  gocyclo:
    min-complexity: 15
  nestif:
    min-complexity: 4

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
