# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # Main CLI
  - id: alert-menta
    main: ./cmd/main.go
    binary: alert-menta
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # MCP Server
  - id: alert-menta-mcp
    main: ./cmd/mcp/main.go
    binary: alert-menta-mcp
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  # First Response
  - id: alert-menta-firstresponse
    main: ./cmd/firstresponse/main.go
    binary: alert-menta-firstresponse
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

  # Triage
  - id: alert-menta-triage
    main: ./cmd/triage/main.go
    binary: alert-menta-triage
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - tar.gz
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - .alert-menta.user.yaml

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: 3-shake
    name: alert-menta
  draft: false
  prerelease: auto
  name_template: "{{.Tag}}"
  header: |
    ## What's Changed in {{.Tag}}

    ### Installation
    ```bash
    # Download and extract
    curl -sLJO https://github.com/3-shake/alert-menta/releases/download/{{.Tag}}/alert-menta_Linux_x86_64.tar.gz
    tar -xzf alert-menta_Linux_x86_64.tar.gz
    ```
  footer: |
    ---
    **Full Changelog**: https://github.com/3-shake/alert-menta/compare/{{.PreviousTag}}...{{.Tag}}
