package firstresponse

import (
	"bytes"
	"fmt"
	"os"
	"text/template"
)

// DefaultGuideTemplate is the default first response guide template
const DefaultGuideTemplate = `<!-- alert-menta:first-response -->
## {{.SeverityEmoji}} インシデント対応ガイド

**重大度**: {{.Severity}} {{.SeverityEmoji}}
{{if .Issue.Title}}**Issue**: {{.Issue.Title}}{{end}}

---

### Step 1: 状況確認 (今すぐ)
以下のコマンドで状況を把握してください:
` + "```" + `
/describe
` + "```" + `

### Step 2: 影響範囲の確認
- [ ] ユーザー影響の有無を確認
- [ ] 影響を受けているサービス/リージョンを特定
- [ ] 発生頻度を確認（継続中 or 断続的）

### Step 3: コミュニケーション
{{if .SlackChannel}}- {{.SlackChannel}} チャンネルで報告{{else}}- Slackの #incidents チャンネルで報告{{end}}
- 必要に応じてエスカレーション
{{if .OnCallTeam}}
**オンコール担当**: {{range .OnCallTeam}}{{.}} {{end}}
{{end}}

### Step 4: 調査開始
類似インシデントと対応手順を確認:
` + "```" + `
/runbook
` + "```" + `

根本原因を分析:
` + "```" + `
/analysis
` + "```" + `

---

### 利用可能なコマンド
| コマンド | 説明 |
|----------|------|
{{range .Commands}}| ` + "`" + `/{{.Name}}` + "`" + ` | {{.Description}} |
{{end}}

---

{{if .EscalationTimeout}}⏱️ 対応開始から{{.EscalationTimeout}}経過しても解決の目処が立たない場合は、エスカレーションを検討してください。{{end}}

<sub>🤖 Generated by alert-menta first-response</sub>
`

// HighSeverityTemplate is the template for high severity incidents
const HighSeverityTemplate = `<!-- alert-menta:first-response -->
## 🔴 緊急インシデント対応ガイド

**重大度**: HIGH (Sev1) 🔴
{{if .Issue.Title}}**Issue**: {{.Issue.Title}}{{end}}

---

### ⚡ 即座に実行

1. **コミュニケーション開始**
   {{if .SlackChannel}}- {{.SlackChannel}} に参加{{else}}- #incident-war-room に参加{{end}}
   - ステータス更新を開始

2. **状況把握**
   ` + "```" + `
   /describe
   ` + "```" + `

3. **影響範囲の確認**
   - [ ] 本番環境への影響を確認
   - [ ] ユーザー数/リクエスト数への影響
   - [ ] データ整合性の確認

### 🔍 調査フェーズ

4. **根本原因分析**
   ` + "```" + `
   /analysis
   ` + "```" + `

5. **対応手順の確認**
   ` + "```" + `
   /runbook
   ` + "```" + `

### 📋 チェックリスト
- [ ] インシデント宣言完了
- [ ] 関係者への通知完了
- [ ] 原因特定
- [ ] 一時対応実施
- [ ] 恒久対応計画策定

---

{{if .OnCallTeam}}**エスカレーション先**: {{range .OnCallTeam}}{{.}} {{end}}{{end}}

⏱️ **15分以内**に解決の目処が立たない場合は即座にエスカレーションしてください。

<sub>🤖 Generated by alert-menta first-response</sub>
`

// Generator generates first response guides
type Generator struct {
	config   *Config
	commands []CommandInfo
}

// NewGenerator creates a new guide generator
func NewGenerator(config *Config, commands []CommandInfo) *Generator {
	return &Generator{
		config:   config,
		commands: commands,
	}
}

// Generate generates a first response guide for the given issue
func (g *Generator) Generate(issue IssueSummary, body string) (string, error) {
	// Determine severity
	severity := DetermineSeverity(issue.Labels, body)

	// Prepare template data
	data := TemplateData{
		Issue:         issue,
		Severity:      string(severity),
		SeverityEmoji: SeverityEmoji(severity),
		Commands:      g.commands,
	}

	// Set escalation timeout based on severity
	switch severity {
	case SeverityHigh:
		data.EscalationTimeout = "15分"
	case SeverityMedium:
		data.EscalationTimeout = "30分"
	case SeverityLow:
		data.EscalationTimeout = "1時間"
	}

	// Find matching guide configuration
	for _, guide := range g.config.Guides {
		if guide.Severity == string(severity) {
			data.OnCallTeam = guide.AutoNotify
			// If custom template file is specified, try to load it
			if guide.Template != "" {
				content, err := os.ReadFile(guide.Template)
				if err == nil {
					return g.renderTemplate(string(content), data)
				}
				// Fall through to default if file not found
			}
		}
	}

	// Use built-in template based on severity
	var templateStr string
	switch severity {
	case SeverityHigh:
		templateStr = HighSeverityTemplate
	default:
		templateStr = DefaultGuideTemplate
	}

	return g.renderTemplate(templateStr, data)
}

// renderTemplate renders a template with the given data
func (g *Generator) renderTemplate(templateStr string, data TemplateData) (string, error) {
	tmpl, err := template.New("guide").Parse(templateStr)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}
